"""add refresh_tokens table

Revision ID: 6c96678f4c71
Revises: e8a1c6b2d9f0
Create Date: 2026-07-25 21:53:53.070736

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c96678f4c71'
down_revision = 'e8a1c6b2d9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
